version: "3"

services:
    alfresco:
        image: ${REPOSITORY_IMAGE}:${REPOSITORY_TAG}
        environment:
            JAVA_OPTS : "
                -Ddb.driver=org.postgresql.Driver
                -Ddb.username=alfresco
                -Ddb.password=alfresco
                -Ddb.url=jdbc:postgresql://postgres:5432/alfresco
                -Dsolr.host=solr6
                -Dsolr.port=8983      
                -Dalfresco.protocol=http
                -Dsolr.secureComms=none
                -Dalfresco.secureComms=none
                -Dsolr.base.url=/solr
                -Dindex.subsystem.name=solr6
                -Dalfresco.restApi.basicAuthScheme=true
                -Dcsrf.filter.enabled=false
                -Dcors.enabled=false
                -Dmessaging.broker.url=\"failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true\"
                "
        ports:
            - ${REPOSITORY_PORT}:8080 #Browser 
            - "7070:7070" #SSL Browser port for Alfresco

    share:
        image: ${SHARE_IMAGE}:${SHARE_TAG}
        environment:
            - REPO_HOST=alfresco
            - REPO_PORT=8080
        ports:
            - ${SHARE_PORT}:8080

    postgres:
        image: ${POSTGRES_IMAGE}:${POSTGRES_TAG}
        environment:
            - POSTGRES_PASSWORD=alfresco
            - POSTGRES_USER=alfresco
            - POSTGRES_DB=alfresco
        ports:
            - ${POSTGRES_PORT}:5432

# Search Services
    solr6:
        image: ${SEARCH_IMAGE}:${SEARCH_TAG}
        environment:
            #Solr needs to know how to register itself with Alfresco
            - SOLR_ALFRESCO_HOST=alfresco
            - SOLR_ALFRESCO_PORT=8080
            #Alfresco needs to know how to call solr
            - SOLR_SOLR_HOST=solr6
            - SOLR_SOLR_PORT=8983
            #Create the default alfresco and archive cores
            - SOLR_CREATE_ALFRESCO_DEFAULTS=alfresco,archive
            - ALFRESCO_SECURE_COMMS=none 
        ports:
            - 8083:8983 #Browser port

    activemq:
        image: alfresco/alfresco-activemq:5.15.6
        ports:
           - 8161:8161 # Web Console
           - 5672:5672 # AMQP
           - 61616:61616 # OpenWire
           - 61613:61613 # STOMP